package com.example.equili.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * CategoryModel represents a spending category in the database.
 * Each user can have their own set of custom categories.
 */
@Entity(tableName = "category_table")
data class CategoryModel(

    /** Unique ID for the category, automatically generated by Room. */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    /** The email of the user who owns this category. Used to filter categories by user. */
    val userEmail: String,

    /** The display name of the category (e.g., "Food", "Transport"). */
    val name: String
)
